create table public.signups (
  signup_id bigint generated by default as identity not null,
  cw_year integer not null,
  signup_timestamp timestamp with time zone not null,
  full_name text not null,
  email text not null,
  contact_number text null,
  representing_institution text null,
  participation_type text null,
  institution_id integer null,
  institution_name_raw text null,
  institution_full_name text null,
  institution_any_issues text null,
  institution_name_for_match text null,
  institution_name_norm text null,
  institution_has_taken_part_before text null,
  previous_institution_flag text null,
  institution_role text null,
  institution_instagram text null,
  head_name text null,
  head_email text null,
  head_contact_number text null,
  rep_name text null,
  rep_email text null,
  rep_contact_number text null,
  country text null,
  country_code text null,
  state_region text null,
  city text null,
  country_raw_primary text null,
  country_other_raw text null,
  final_country_raw text null,
  country_joined_raw text null,
  region_uk_raw text null,
  region_us_raw text null,
  state_raw text null,
  shipping_address text null,
  board_members_count integer null,
  approx_members_count integer null,
  heard_about_cw text null,
  contact_preferences text null,
  consent_confirmed text null,
  institution_match_status text null,
  match_source text null,
  raw_row_number integer null,
  raw_source_form_version text null,
  created_at timestamp with time zone not null default now(),
  constraint signups_pkey primary key (signup_id),
  constraint signups_institution_id_fkey foreign KEY (institution_id) references institutions (institution_id)
) TABLESPACE pg_default;

create index IF not exists signups_cw_year_idx on public.signups using btree (cw_year) TABLESPACE pg_default;

create index IF not exists signups_institution_id_idx on public.signups using btree (institution_id) TABLESPACE pg_default;

create index IF not exists signups_country_code_cw_year_idx on public.signups using btree (country_code, cw_year) TABLESPACE pg_default;

create index IF not exists signups_email_idx on public.signups using btree (email) TABLESPACE pg_default;

create trigger trg_prepare_signup_for_match
before insert or update of institution_id
on public.signups
for each row
execute function public.fn_prepare_signup_for_match();

create trigger trg_capture_unmatched_institution
after INSERT on signups for EACH row
execute FUNCTION fn_capture_unmatched_institution ();


create table public.institution_review (
  review_id bigserial not null,
  review_source text not null default 'signup'::text,
  cw_year integer not null,
  match_scope_key text not null default ''::text,
  country text null,
  country_code text null,
  institution_name_for_match text null,
  institution_name_norm text null,
  representing_institution text null,
  participation_type text null,
  n_signups integer not null default 0,
  alias_institution_id integer null,
  resolve_via text null,
  status text not null default 'pending'::text,
  suggested_institution_id integer null,
  suggested_institution_name text null,
  confidence integer null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint institution_review_pkey primary key (review_id),
  constraint institution_review_source_cw_year_scope_name_key unique (review_source, cw_year, match_scope_key, institution_name_norm),
  constraint institution_review_alias_institution_id_fkey foreign KEY (alias_institution_id) references institutions (institution_id)
) TABLESPACE pg_default;

create trigger trg_resolve_institution_review
before
update OF alias_institution_id on institution_review for EACH row
execute FUNCTION fn_resolve_institution_review ();

create trigger trg_resolve_institution_review_alias
after
update OF alias_institution_id on institution_review for EACH row
execute FUNCTION fn_resolve_institution_review_alias ();

create table public.institutions (
  institution_id integer generated by default as identity not null,
  parent_id integer null,
  country text not null,
  country_code text not null,
  name_canonical text not null,
  name_display text null,
  institution_name_norm text not null,
  legacy_ids jsonb null default '[]'::jsonb,
  aliases jsonb null default '[]'::jsonb,
  constraint institutions_pkey primary key (institution_id)
) TABLESPACE pg_default;

create index IF not exists institutions_name_norm_idx on public.institutions using btree (institution_name_norm) TABLESPACE pg_default;

create trigger trg_initialize_institution_parent_id
before insert on public.institutions
for each row
execute function public.fn_initialize_institution_parent_id();

create trigger trg_auto_match_on_new_institution
after insert on public.institutions
for each row
execute function public.fn_auto_match_on_new_institution();


create index IF not exists institutions_name_norm_idx on public.institutions using btree (institution_name_norm) TABLESPACE pg_default;


create table public.institution_aliases (
  alias_id            bigserial primary key,
  institution_id      integer not null references public.institutions(institution_id),
  country_code        text not null,
  alias_name          text not null,
  alias_name_norm     text not null,
  created_at          timestamptz not null default now(),
  unique (institution_id, alias_name_norm)
) TABLESPACE pg_default;

create index if not exists institution_aliases_name_norm_idx
  on public.institution_aliases using btree (alias_name_norm, country_code) TABLESPACE pg_default;

create trigger trg_auto_match_on_alias_insert
after insert on public.institution_aliases
for each row
execute function public.fn_auto_match_on_alias_insert();
