create table public.fundraising (
  sponsor_id           bigint generated by default as identity not null,
  cw_year              integer not null,
  community_sponsor_id integer not null,                                        -- external ID from CW system
  institution_name     text not null,                                           -- name as it appears in the sponsorship data
  institution_id       integer null,                                            -- FK to institutions (null if not a known institution)
  institution_name_for_match text null,
  institution_name_norm text null,
  institution_match_status text null,
  match_source         text null,
  region               text null,
  state                text null,
  launch_good          numeric(12,2) not null default 0,
  venmo                numeric(12,2) not null default 0,
  check_amount         numeric(12,2) not null default 0,                        -- "check" is a reserved word
  school_check         numeric(12,2) not null default 0,
  corporate_match      numeric(12,2) not null default 0,
  money_order_other    numeric(12,2) not null default 0,
  total                numeric(12,2) not null default 0,
  banking_status       text null,                                               -- 'Banked', 'Not Banked', 'Confirmed - No Donations'
  notes                text null,
  created_at           timestamptz not null default now(),
  constraint fundraising_pkey primary key (sponsor_id),
  constraint fundraising_cw_year_csid_key unique (cw_year, community_sponsor_id),
  constraint fundraising_institution_id_fkey foreign key (institution_id) references public.institutions(institution_id)
) tablespace pg_default;

create index if not exists fundraising_cw_year_idx
  on public.fundraising using btree (cw_year) tablespace pg_default;

create index if not exists fundraising_institution_id_idx
  on public.fundraising using btree (institution_id) tablespace pg_default;

create index if not exists fundraising_cw_year_name_norm_idx
  on public.fundraising using btree (cw_year, institution_name_norm) tablespace pg_default;

create index if not exists fundraising_banking_status_idx
  on public.fundraising using btree (banking_status) tablespace pg_default;
